dist: trusty
language: c
sudo: required
env:
  - BOARD=CORE
  - BOARD=MINDEV
  - BOARD=SWIMCOM
cache:
  directories:
    - $HOME/sdcc
install: sh -e test/deps.sh
script: PATH=$PATH:$HOME/sdcc/bin make BOARD=$BOARD
